import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav></Nav>
        {children}{/* 路由出口 */}
      </body>
    </html>
  );
}
